compact_mode=no
info_button=yes
screenshot_button=yes
loop_button=yes
download_button=no
jump_amount=5
jump_more_amount=60
bottom_hover=yes
bottom_hover_zone=280
window_top_bar=auto
window_controls=yes
show_title=yes
title_font_size=26
time_font_size=24
description_font_size=22
playpause_size=40
midbuttons_size=32
sidebuttons_size=32
scale_windowed=1.25
scale_fullscreen=2.00
scale_forced_window=1.25
hide_timeout=1800
